// @generated by scripts/generate-edge-contracts.mjs; do not edit.
// schema-sha256: c741148976917bc058da6e28f0827a87201db22b9df00bea4b752c6ce0b01ba0
pub const EDGE_PROTOCOL_V2: &str = "cowd.edge.v2";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeBootstrapRequest {
    pub protocol: String,
    pub gateway_version: String,
    pub surface_id: String,
    pub driver_profile: String,
    #[serde(default)]
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeBootstrapResponse {
    pub protocol: String,
    pub surface_id: String,
    pub driver_profile: String,
    pub capabilities: Vec<String>,
    pub max_in_flight: usize,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeEventEnvelope {
    pub sequence: u64,
    pub frame: SurfaceFrame,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EdgeEventAck {
    pub sequence: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EdgeSourceStreamMeta {
    pub chunk_index: usize,
    pub final_chunk: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EdgeSourceRevision {
    #[serde(default)]
    pub expected_revision: Option<u64>,
    pub revision: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceFieldSchema { pub name: String, pub data_type: String, pub nullable: bool }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceTableSchema { pub table_name: String, pub fields: Vec<SourceFieldSchema>, pub primary_key: Vec<String> }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct SourceBatchCursor { pub offset: usize, pub limit: usize, #[serde(default)] pub next_offset: Option<usize> }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceReadPlan { pub adapter_id: String, pub resource_ref: String, #[serde(default)] pub table: Option<String>, #[serde(default)] pub fields: Vec<String>, #[serde(default)] pub limit: Option<usize>, #[serde(default)] pub offset: Option<usize>, #[serde(default)] pub cursor: Option<String>, #[serde(default)] pub metadata: Value }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceRecordBatch { pub adapter_id: String, pub resource_ref: String, #[serde(default)] pub table: Option<String>, pub schema: SourceTableSchema, pub rows: Vec<Value>, pub cursor: SourceBatchCursor, pub row_count: usize, pub checksum: String, pub truncated: bool }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceWatermark { pub adapter_id: String, pub resource_ref: String, #[serde(default)] pub table: Option<String>, pub strategy: String, #[serde(default)] pub cursor: Option<String>, #[serde(default)] pub offset: Option<usize>, #[serde(default)] pub high_watermark: Option<String>, #[serde(default)] pub checksum: Option<String>, #[serde(default)] pub revision: u64, pub updated_at_ms: i64 }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceIncrementalRunRequest { pub adapter_id: String, pub resource_ref: String, #[serde(default)] pub table: Option<String>, #[serde(default)] pub limit: Option<usize>, #[serde(default)] pub watermark: Option<SourceWatermark>, #[serde(default)] pub expected_revision: Option<u64>, #[serde(default)] pub metadata: Value }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceIngestionReceipt { pub receipt_id: String, pub adapter_id: String, pub resource_ref: String, pub row_count: usize, pub checksum: String, #[serde(default)] pub watermark_before: Option<SourceWatermark>, #[serde(default)] pub watermark_after: Option<SourceWatermark>, #[serde(default)] pub matrix_refs: Vec<String>, pub created_at_ms: i64 }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceIncrementalRunResult { pub status: String, #[serde(default)] pub chunk_index: usize, #[serde(default = "edge_source_default_true")] pub final_chunk: bool, #[serde(default)] pub batch: Option<SourceRecordBatch>, #[serde(default)] pub watermark_before: Option<SourceWatermark>, #[serde(default)] pub watermark_after: Option<SourceWatermark>, #[serde(default)] pub degraded_reason: Option<String>, #[serde(default)] pub receipt: Option<SourceIngestionReceipt> }

const fn edge_source_default_true() -> bool { true }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceEventBatch { pub adapter_id: String, #[serde(default)] pub resource_ref: Option<String>, #[serde(default)] pub events: Vec<Value>, pub event_count: usize, #[serde(default)] pub watermark_after: Option<SourceWatermark> }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceConnectorState { pub adapter_id: String, pub surface_id: String, pub status: String, #[serde(default)] pub capabilities: Vec<String>, #[serde(default)] pub last_run_at_ms: Option<i64>, #[serde(default)] pub last_error: Option<String>, #[serde(default)] pub degraded_reason: Option<String>, #[serde(default)] pub watermarks: Vec<SourceWatermark> }
