// @generated by scripts/generate-edge-contracts.mjs; do not edit.
// schema-sha256: b75aa5d5bfa21afa0899828de3ba43349bae5754c60af95f79cd3a895cc13ed7
pub const EDGE_PROTOCOL_V2: &str = "cowd.edge.v2";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeBootstrapRequest {
    pub protocol: String,
    pub gateway_version: String,
    pub surface_id: String,
    pub driver_profile: String,
    #[serde(default)]
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeBootstrapResponse {
    pub protocol: String,
    pub surface_id: String,
    pub driver_profile: String,
    pub capabilities: Vec<String>,
    pub max_in_flight: usize,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeEventEnvelope {
    pub sequence: u64,
    pub frame: SurfaceFrame,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EdgeEventAck {
    pub sequence: u64,
}
