// @generated by scripts/generate-driver-profiles.mjs; do not edit.
#[derive(Debug, Clone, Copy)]
pub struct DriverProfile {
    pub id: &'static str,
    pub surface_id: &'static str,
    pub artifact: &'static str,
    pub adapter_id: &'static str,
    pub default_base_url: &'static str,
    pub capabilities: &'static [&'static str],
}

pub const DRIVER_PROFILES: &[DriverProfile] = &[
    DriverProfile { id: "feishu-message", surface_id: "feishu", artifact: "cowd-edge-open-platform-message", adapter_id: "", default_base_url: "", capabilities: &["message.ingress", "message.egress", "message.send.text", "message.send.image", "message.send.voice", "message.send.document", "message.send.video", "message.send.card", "message.edit", "message.delete", "message.chat.info", "message.callback", "message.health", "message.processing.lifecycle"] },
    DriverProfile { id: "email-message", surface_id: "email", artifact: "cowd-edge-email-message", adapter_id: "", default_base_url: "", capabilities: &["message.ingress", "message.egress", "message.send.text", "message.send.document", "message.smtp", "message.imap", "message.health"] },
    DriverProfile { id: "wecom-message", surface_id: "wecom", artifact: "cowd-edge-wecom-message", adapter_id: "", default_base_url: "", capabilities: &["message.ingress", "message.egress", "message.send.text", "message.callback", "message.crypto", "message.health"] },
    DriverProfile { id: "wechat-ilink-message", surface_id: "wechat-ilink", artifact: "cowd-edge-wechat-ilink-message", adapter_id: "", default_base_url: "", capabilities: &["message.ingress", "message.egress", "message.send.text", "message.send.image", "message.chat.info", "message.qr_login", "message.long_poll", "message.health"] },
    DriverProfile { id: "feishu-bitable", surface_id: "feishu-bitable", artifact: "cowd-edge-bitable-source", adapter_id: "feishu_bitable", default_base_url: "https://open.feishu.cn", capabilities: &["source.schema_discovery", "source.snapshot", "source.incremental", "source.event", "source.health"] },
    DriverProfile { id: "lark-bitable", surface_id: "lark-bitable", artifact: "cowd-edge-bitable-source", adapter_id: "lark_bitable", default_base_url: "https://open.larksuite.com", capabilities: &["source.schema_discovery", "source.snapshot", "source.incremental", "source.event", "source.health"] },
    DriverProfile { id: "postgres", surface_id: "postgres", artifact: "cowd-edge-sql-source", adapter_id: "postgres", default_base_url: "", capabilities: &["source.schema_discovery", "source.snapshot", "source.incremental", "source.event", "source.health"] },
    DriverProfile { id: "mysql", surface_id: "mysql", artifact: "cowd-edge-sql-source", adapter_id: "mysql", default_base_url: "", capabilities: &["source.schema_discovery", "source.snapshot", "source.incremental", "source.event", "source.health"] },
    DriverProfile { id: "mariadb", surface_id: "mariadb", artifact: "cowd-edge-sql-source", adapter_id: "mariadb", default_base_url: "", capabilities: &["source.schema_discovery", "source.snapshot", "source.incremental", "source.event", "source.health"] },
];

pub fn driver_profile(id: &str) -> Option<&'static DriverProfile> {
    DRIVER_PROFILES.iter().find(|profile| profile.id == id)
}
